#!/bin/ksh
set -eu

output_file="$1"

cabal v2-install exe:xmonad-config --overwrite-policy=always --install-method=copy

[ -f "${output_file}" ] && mv -f -- "${output_file}" "${output_file}.old"
install -- "${HOME}/.cabal/bin/xmonad-config" "${output_file}"
