#!/usr/bin/env perl

# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

# TODO:
# Review Number::Bytes::Human to see exactly how it does what it does.
#
# The whole thing could be pledged so that it doesn't use capabilities
# it doesn't need.

use strict;
use warnings;
use File::Basename 'fileparse';
use Number::Bytes::Human 'format_bytes';

my $separator = ' | ';

my $filename = shift // die "Need a file name.\n";
my $basename = fileparse $filename;

my $width = shift // die "Need a width.\n";
my $height = shift // die "Need a height.\n";
my $geometry = $width . 'x' . $height;

my $file_size = (stat $filename)[7];
$file_size = format_bytes $file_size;

print $file_size . $separator . $geometry . $separator . $basename;
