#!/usr/bin/env perl

# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

# TODO:
# Review Number::Bytes::Human to see exactly how it does what it does.

use strict;
use warnings;
use File::Basename 'fileparse';
use Number::Bytes::Human 'format_bytes';
use OpenBSD::Pledge;
use OpenBSD::Unveil;

pledge( qw(rpath unveil) ) or die "Pledge failed: $!\n";

my $separator = ' | ';

my $filename = shift // die "Need a file name.\n";
my $basename = fileparse $filename;

unveil($filename, 'r') or die "Unveil failed: $!\n";
pledge( qw(rpath) ) or die "Pledge failed: $!\n";

my $width = shift // die "Need a width.\n";
my $height = shift // die "Need a height.\n";
my $geometry = $width . 'x' . $height;

my $file_size = format_bytes( (stat $filename)[7] );

print $file_size . $separator . $geometry . $separator . $basename;
