#!/bin/sh
# shellcheck disable=SC1090

set -eu

readonly COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
. "${COLORS_SH}"


menu() {
	dmenu -i -fn 'mono-12' \
		-nb "${background:-#040516}" \
		-nf "${color3:-#9974e7}" \
		-sb "${background:-#040516}" \
		-sf "${foreground:-#e0cef3}" \
		"$@"
}


while read -r file; do
	case "$1" in
		# copy file with filehandler
		'c')
			filehandler copy "${file}"
			;;

		# delete file
		'd')
			really_delete="$(
				{
				echo 'Yes'
				echo 'No'
				} | menu -p "Really delete ${file}?"
			)"

			[ "${really_delete}" = 'Yes' ] && {
				rm -- "${file}"
				notify-send -- "${file} deleted."
			}
			;;

		# move file with filehandler
		'm')
			filehandler move "${file}"
			;;

		# rename file with filehandler
		'n')
			filehandler rename "${file}"
			;;

		# rotate clockwise
		'r')
			convert -rotate 90 -- "${file}" "${file}"
			;;

		# rotate counter-clockwise
		'R')
			convert -rotate -90 -- "${file}" "${file}"
			;;

		# horizontally invert file, aka 'flop' it
		'f')
			convert -flop -- "${file}" "${file}"
			;;

		# yank the relative file path
		'y')
			printf '%s' "${file}" | xclip -selection clipboard
			notify-send -- "${file} copied to clipboard."
			;;

		# yank the absolute file path
		'Y')
			ABSOLUTE_PATH="$(readlink -f -- "${file}")"

			printf '%s' "${ABSOLUTE_PATH}" | xclip -selection clipboard
			notify-send -- "${ABSOLUTE_PATH} copied to clipboard."
			;;

		*)
			err 'Key not bound.'
			;;

	esac
done
