# shellcheck disable=SC1090

if command -v 'doas' > /dev/null 2>&1; then
	alias priv='doas '
elif command -v 'sudo' > /dev/null 2>&1; then
	alias priv='sudo '
fi

# if tmux is installed and not inside a tmux session, then try to attach.
# if attachment fails, start a new session
command -v 'tmux' > /dev/null 2>&1 &&
	[ -z "${TMUX}" ] &&
	{ tmux attach || tmux; } > /dev/null 2>&1

# enable ^T for status, useful for dd(1)
stty status "^T"

# ksh options
set -o vi

# shellcheck disable=SC3040
case "${KSH_VERSION%%\ KSH*}" in
	'@(#)PD') set -o vi-show8 ;;
esac

# needs to happen for each shell invocation
GPG_TTY="$(tty)"
export GPG_TTY

for srcfile in 'aliases' 'completions' 'functions' 'prompt'; do
	. "${XDG_CONFIG_HOME}/ksh/${srcfile}"
done
